services:
  - type: web
    name: diario-ia-api
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -m textblob.download_corpora
    startCommand: "gunicorn app:app"
